apiVersion: v1
kind: Secret
metadata:
  name: vault-token
type: Opaque
data:
  token: 'aHZzLkNBRVNJSnpfWS1oM1BmQk5xeGFVTXdldVdUdEZmNGNsMExWdHJ6OHRubHF2REFBeEdoNEtI
R2gyY3k1c2JIRk5aRVpCZUdGaGNtVlhTMHh2WTFkV1owVk5SMVU='